[package]
name = "jsonbee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.202"
serde_json = "1.0.117"

[dev-dependencies]
assert_cmd = "2.0.14"
duct = "0.13.7"
predicates = "3.1.0"
